### ISSUE TITLE
KeeperFX Config Diff Tool should keep name on top

### ISSUE THREAD

**Issue by Loobinex** [dkfans/keeperfx-website#14]
If you take this input:

LEFT
```
[attributes]
Name = BARBARIAN
NameTextID = 275
Health = 700
```
RIGHT
```
[attributes]
Name = BARBARIAN
NameTextID = 275
Health = 500
```

You get this result:

```
[attributes]
Health = 500
Name = BARBARIAN
```

With the name all the way at the bottom. This is not nice at all.

**Comment by yani** [comment]
Fixed in https://github.com/dkfans/keeperfx-website/commit/0623eab268cb0b3aecea7ef4acbba928a7d0095d

All 'Name' properties will be moved to the top now.
